- name: Demon on variables
  hosts: local
  connection: local
  vars_files: 
   -course.yaml
  tasks: 
   - name: Print variables
     debug:
     msg: "I am Leaning {{COURSE}} from {{TRAINER}} with {{DURATION}}"
