- name: Demo on variables
  hosts: local
  connection: local
  vars_files: 
   - course.yaml
  tasks: 
   - name: Print variables
     vars:
       COURSE: "DEVSECOPS - AIOPS & MLOPS"
     debug:
       msg: "I am Leaning {{COURSE}} from {{TRAINER}} with {{DURATION}}"