- name: Install and start nginx
  hosts: frontend
  become: yes
  tasks:
   - name: install nginx
     package:
      name: nginx
   - name: start nginx
     service:
      name: nginx
      state: started
      enable: yes
    
   