- name: Demo on variables
  hosts: local
  connection: local
  vars:
   COURSE: "Anisbe"
   TRAINER: "Siva Kumar"
   DURATION: "150HRS"
  tasks:
  - name: Print Variables
    vars:
     COURSE: "DEVSECOPS with AiOPs and MLOPS"
    debug:
     msg: "Hello.. I am Learing {{COURSE}}, from {{TRAINER}} and its duration is {{DURATION}}"
